# Generated by Django 6.0.3 on 2026-03-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('register', 'Register'), ('password_reset', 'Password Reset'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('user_created', 'User Created'), ('user_role_changed', 'User Role Changed'), ('user_deactivated', 'User Deactivated'), ('user_activated', 'User Activated'), ('user_password_reset', 'User Password Reset'), ('user_deleted', 'User Deleted'), ('consent_granted', 'Consent Granted'), ('consent_revoked', 'Consent Revoked'), ('medical_record_viewed', 'Medical Record Viewed'), ('medical_record_created', 'Medical Record Created'), ('medical_record_updated', 'Medical Record Updated'), ('emergency_access', 'Emergency Access')], db_index=True, max_length=30),
        ),
    ]
