# Generated by Django 6.0.1 on 2026-01-31 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the invitee', max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique invitation token', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was created')),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this invitation has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the invitation was used', null=True)),
                ('sent_by', models.ForeignKey(help_text='Admin user who sent this invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, help_text='User who registered with this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
