# Generated by Django 6.0.1 on 2026-02-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_recovery_codes',
            field=models.JSONField(blank=True, default=list, help_text='Hashed recovery codes for MFA (one-time use)', null=True),
        ),
    ]
