# Generated by Django 6.0.1 on 2026-01-30 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(help_text="e.g., 'Cardiology', 'Radiology'", max_length=100)),
                ('description', models.TextField(help_text='Description of what this consent allows')),
                ('is_granted', models.BooleanField(default=True, help_text='Whether consent is currently active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When temporary access expires (null for permanent)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent',
                'verbose_name_plural': 'Consents',
                'ordering': ['-updated_at'],
                'unique_together': {('patient', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ConsentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='User who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_actions', to=settings.AUTH_USER_MODEL)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consents.consent')),
            ],
            options={
                'verbose_name': 'Consent History',
                'verbose_name_plural': 'Consent Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
